const state={stocks:[],insufficient:[],blacklist:[],wishlist:[],nasdaq:[],sp500:[],companies:new Map(),tab:"wishlist",range:"below",query:""};
const $=s=>document.querySelector(s);
const fmt=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n);
const poolConfig={wishlist:{label:"WISHLIST",eyebrow:"WISHLIST · WEEKLY SIGNAL",intro:"Start with the stocks you care about and see how far they are from their 200-week average."},nasdaq:{label:"NASDAQ-100",eyebrow:"NASDAQ-100 · WEEKLY SIGNAL",intro:"See how Nasdaq-100 constituents compare with their long-term trend."},sp500:{label:"S&P 500",eyebrow:"S&P 500 · WEEKLY SIGNAL",intro:"Look for long-term trend signals across the broader S&P 500 universe."}};
let deployedRevision=null;
async function checkForUpdate(){try{const r=await fetch(`version.json?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)return;const {revision}=await r.json();if(deployedRevision&&revision&&revision!==deployedRevision){location.reload();return}deployedRevision=revision||deployedRevision}catch(e){}}
function weekLabel(value){if(!value)return "Unknown week";const date=new Date(`${value.slice(0,10)}T12:00:00Z`),day=date.getUTCDay()||7;date.setUTCDate(date.getUTCDate()+4-day);const year=date.getUTCFullYear(),start=new Date(Date.UTC(year,0,1));return `Week ${Math.ceil((((date-start)/86400000)+1)/7)}, ${year}`}
function normalize(values){const byName=new Map([...state.companies].map(([s,n])=>[n.toUpperCase(),s]));return [...new Set(values.map(v=>{const x=v.trim().toUpperCase();return state.companies.has(x)?x:byName.get(x)||x}).filter(Boolean))]}
async function init(){try{const urls=["stocks.json","blacklist.json","watchlist.json","nasdaq100.json","sp500.json"].map(x=>fetch(`data/${x}`,{cache:"no-cache"}));const [dataRes,blackRes,wishRes,nasRes,spRes]=await Promise.all(urls);if(!dataRes.ok)throw new Error();const data=await dataRes.json();state.stocks=data.stocks||[];state.insufficient=data.insufficient_history||[];state.nasdaq=nasRes.ok?await nasRes.json():[];state.sp500=spRes.ok?await spRes.json():[];state.companies=new Map([...state.nasdaq,...state.sp500]);state.blacklist=normalize(blackRes.ok?await blackRes.json():[]);state.wishlist=normalize(wishRes.ok?await wishRes.json():[]);const dates=state.stocks.map(x=>x.updated).filter(Boolean).sort();$("#asof").textContent=dates.length?`Updated ${weekLabel(dates.at(-1))}`:"Awaiting first scan";render()}catch(e){$("#stock-list").innerHTML='<div class="empty"><p>No market data yet</p><small>Run the local update script first.</small></div>';updateStats([])}}
function poolSymbols(){return state.tab==="wishlist"?state.wishlist:(state.tab==="nasdaq"?state.nasdaq:state.sp500).map(x=>x[0])}
function belongs(symbol,pool){return (pool==="nasdaq"?state.nasdaq:state.sp500).some(x=>x[0]===symbol)}
function inRange(d){return Number.isFinite(d)&&(state.range==="below"?d<0:d>=0&&d<Number(state.range))}
function poolRows(){const symbols=poolSymbols(),rows=symbols.map(symbol=>state.stocks.find(s=>s.symbol===symbol)).filter(Boolean);return rows.filter(s=>!state.blacklist.includes(s.symbol)&&inRange(s.distance)&&(!state.query||`${s.symbol} ${s.name}`.toLowerCase().includes(state.query))).sort((a,b)=>Math.abs(a.distance)-Math.abs(b.distance))}
function tags(symbol){
  if(!state.wishlist.includes(symbol))return [];
  return [
    "Wishlist",
    `Nasdaq-100 ${belongs(symbol,"nasdaq")?"✓":"—"}`,
    `S&P 500 ${belongs(symbol,"sp500")?"✓":"—"}`
  ];
}
function badgeMarkup(symbol){const labels=tags(symbol);return labels.length?`<div class="badges">${labels.map(x=>`<i>${x}</i>`).join("")}</div>`:""}
function render(){const cfg=poolConfig[state.tab];$("#eyebrow").textContent=cfg.eyebrow;$("#intro").textContent=cfg.intro;$("#pool-label").textContent=cfg.label;$("#results-title").textContent=state.query?"Search results":"Signals";const rows=poolRows();updateStats(rows);const range=state.range==="below"?"below 200W":`0–${state.range}% above 200W`;$("#result-label").textContent=`${rows.length} stocks · ${range}`;$("#stock-list").innerHTML=rows.length?rows.map(card).join(""):`<div class="empty"><p>No stocks in this range.</p><small>Try widening the range or wait for a later scan.</small></div>`;renderAbove();renderInsufficient();renderBlacklist()}
function updateStats(rows){const symbols=poolSymbols().filter(s=>!state.blacklist.includes(s)),covered=new Set(state.stocks.map(s=>s.symbol));$("#match-count").textContent=rows.length;$("#below-count").textContent=rows.filter(s=>s.distance<0).length;$("#coverage").textContent=`${symbols.filter(s=>covered.has(s)).length}/${symbols.length}`}
function card(s){const below=s.distance<0,label=below?`${Math.abs(s.distance).toFixed(1)}% below`:`${s.distance.toFixed(1)}% above`,width=Math.max(3,Math.min(100,50+s.distance*5));return `<article class="stock-card"><div class="identity"><div class="ticker">${s.symbol}</div><div class="company"><strong>${s.name}</strong><span>200W · ${fmt(s.sma200)}</span>${badgeMarkup(s.symbol)}</div></div><div class="price"><strong>${fmt(s.price)}</strong><span class="distance ${below?"below":""}">${label}</span></div><div class="bar-wrap"><div class="bar"><i style="width:${width}%"></i></div><span>${weekLabel(s.updated)}</span></div></article>`}
function renderAbove(){const threshold=state.range==="below"?0:Number(state.range),symbols=new Set(poolSymbols()),rows=state.stocks.filter(s=>symbols.has(s.symbol)&&!state.blacklist.includes(s.symbol)&&Number.isFinite(s.distance)&&s.distance>=threshold&&(!state.query||`${s.symbol} ${s.name}`.toLowerCase().includes(state.query))).sort((a,b)=>a.distance-b.distance);$("#above-note").hidden=!rows.length;$("#above-count").textContent=rows.length;$("#above-list").innerHTML=rows.map(s=>`<div class="above-row"><strong>${s.symbol}</strong><span>${s.name}${badgeMarkup(s.symbol)}</span><b>+${s.distance.toFixed(2)}%</b></div>`).join("")}
function renderInsufficient(){const symbols=new Set(poolSymbols()),rows=state.insufficient.filter(s=>symbols.has(s.symbol)&&!state.blacklist.includes(s.symbol));$("#history-note").hidden=!rows.length;$("#history-count").textContent=rows.length;$("#history-list").innerHTML=rows.sort((a,b)=>b.weeks-a.weeks).map(s=>`<div class="history-row"><strong>${s.symbol}</strong><span>${s.name} · ${s.weeks}/200 weeks${badgeMarkup(s.symbol)}</span><small>Retry after ${weekLabel(s.retry_after)}</small></div>`).join("")}
function renderBlacklist(){$("#blacklist-count").textContent=state.blacklist.length;$("#blacklist-list").innerHTML=state.blacklist.length?state.blacklist.map(symbol=>`<div class="blacklist-row"><strong>${symbol}</strong><span>${state.companies.get(symbol)||"Excluded"}${badgeMarkup(symbol)}</span><i>Not scanned</i></div>`).join(""):'<div class="blacklist-row empty-row"><span>No stocks are currently excluded</span></div>'}
$(".tabs").addEventListener("click",e=>{if(!e.target.dataset.tab)return;document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x===e.target));state.tab=e.target.dataset.tab;render()});
$("#thresholds").addEventListener("click",e=>{if(!e.target.dataset.value)return;document.querySelectorAll("#thresholds button").forEach(x=>x.classList.toggle("active",x===e.target));state.range=e.target.dataset.value;render()});
$("#search").addEventListener("input",e=>{state.query=e.target.value.trim().toLowerCase();render()});
init();checkForUpdate();setInterval(checkForUpdate,30000);
