const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const elements=new Map();
const context=vm.createContext({Intl,Date,Number,Map,Set,document:{querySelector:s=>{if(!elements.has(s))elements.set(s,{addEventListener(){}});return elements.get(s)}},fetch:()=>new Promise(()=>{}),setInterval(){}});
vm.runInContext(fs.readFileSync('app.js','utf8'),context);
const draw=points=>vm.runInContext(`trendChart(${JSON.stringify(points)})`,context);
const points=[{observed_at:'2026-10-03',fiscal_date_ending:'2026-06-30',eps:2,pe:10},{observed_at:'2026-10-10',fiscal_date_ending:'2026-06-30',eps:2,pe:12}];
const graph=draw(points);
assert.match(graph,/class="eps-series"/);
assert.match(graph,/class="pe-series"/);
assert.equal((graph.match(/<polyline/g)||[]).length,2);
assert.equal((draw([points[0]]).match(/<circle/g)||[]).length,2);
assert.doesNotMatch(draw([points[0]]),/<polyline/);
const gap=draw([points[0],{...points[1],pe:null},{...points[1],observed_at:'2026-10-17'}]);
assert.equal((gap.match(/<polyline/g)||[]).length,1);
assert.doesNotMatch(graph,/NaN|Infinity/);
vm.runInContext(`state.wishlist=['A'];state.earnings={A:{quarters:[{fiscal_date_ending:'2026-06-30',eps:2,eps_ttm:8,reported_date:'2026-07-23',saved_at:'2026-10-03'}],valuations:${JSON.stringify(points)}}};state.stocks=[{symbol:'A',price:80,updated:'2026-10-01'}];renderEarnings()`,context);
assert.match(elements.get('#earnings-list').innerHTML,/10\.0×/);
assert.match(elements.get('#earnings-list').innerHTML,/80\.00/);
vm.runInContext("state.stocks[0].updated='2026-07-01';renderEarnings()",context);
assert.match(elements.get('#earnings-list').innerHTML,/N\/A/);
vm.runInContext(`state.wishlist=['A','C','B'];state.earnings.B=state.earnings.A;state.earnings.C=state.earnings.A;state.stocks.push({symbol:'B',price:40,updated:'2026-10-01'},{symbol:'C',price:160,updated:'2026-10-01'});renderEarnings()`,context);
const cards=elements.get('#earnings-list').innerHTML;
assert.ok(cards.indexOf('<strong>B</strong>')<cards.indexOf('<strong>C</strong>'));
assert.ok(cards.indexOf('<strong>C</strong>')<cards.indexOf('<strong>A</strong>'));
assert.equal((cards.match(/<details class="eps-card">/g)||[]).length,3);
assert.doesNotMatch(cards,/<details[^>]*\bopen\b/);
assert.doesNotMatch(cards.match(/<summary class="eps-summary">[\s\S]*?<\/summary>/)[0],/valuation-chart|Latest stored price/);
console.log('Chart checks passed, including collapsed card summaries and ascending PE with unavailable PE last.');
assert.match(vm.runInContext("card({symbol:'Y',name:'Young stock',price:30,sma200:20,weeks:2,distance:50,updated:'2026-10-09'})",context),/2W ·/);
assert.match(vm.runInContext("card({symbol:'N',name:'Nasdaq stock',price:30,sma200:20,distance:50,updated:'2026-10-09'})",context),/200W ·/);
assert.equal(vm.runInContext("Object.keys(poolConfig).join(',')",context),'wishlist,nasdaq');
